site_name: Django Graphene Auth
site_description: GraphQL registration and authentication for Django
site_url: https://django-graphene-auth.readthedocs.io/en/latest
site_author: ptbang
repo_name: ptbang/django-graphene-auth
repo_url: https://github.com/ptbang/django-graphene-auth

theme:
  name: "material"
  language: en
  palette:
    primary: 'black'
    accent: 'purple'
  logo: 'images/graphql_logo.svg'
  favicon: 'images/favicon.ico'

extra:
  social:
    - type: github-alt
      link: https://github.com/ptbang

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - markdownextradata:
        data: docs/data

dev_addr: 127.0.0.1:7000

nav:
  - Start here: index.md
  - Installation: installation.md
  - Settings: settings.md
  - API: api.md
  - Overriding email templates: overriding-email-templates.md
  - Changelog: changelog.md
